languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "にじてくと"

[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false

  logo = "img/nijitect_logo_r1.png"
  description = "ほむりん(@98tml). 写真撮影,動画編集,Webサイト製作/保守."
  copyright = "&copy;{ year } 穂村田"
  dateFormat = "2006.1.2"

 [author]
   name = "ほむりん"
   image = "img/pFIScid5.jpg"
   headline = "写真・動画撮影、Webサイトの製作・運営をしています"
   bio = "SNSのフォローもお願いいたします！"
   links = [
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
      { x-twitter = "https://x.com/98tml" },
#     { x-twitter = "https://twitter.com/t98ml" },
      { instagram = "https://www.instagram.com/98tml/" },
#     { github = "https://github.com/terminal98" },
#     { discord = "https://discord.gg/invitecode" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { link = "https://t98.info/" },
      { envelope = "https://t98.info/contact/" },
#     { amazon = "https://www.amazon.co.jp/hz/wishlist/ls/3HIW8VNQ3HZUU?tag=uxwfl8kw-22" },
   ]

