# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "プロフィール"
  pageRef = "about"
  weight = 5

[[main]]
  name = "今後の予定"
  pageRef = "eventlist"
  weight = 6

#[[main]]
#  name = "撮影について"
#  weight = 10

#[[main]]
#  name = "撮影・データについて"
#  parent = "撮影について"
#  pageRef = "policy"
#  weight = 11

#[[main]]
#  name = "イベント参加予定"
#  parent = "撮影について"
#  pageRef = "eventlist"
#  weight = 12

[[main]]
  name = "作例"
  url = "https://twitter.com/search?q=%4098tml%20filter%3Amedia%20min_retweets%3A5%20-from%3A98tml&f=image"
  weight = 13

[[main]]
  pre = "twitter"
  name = "X/Twitter"
  url = "https://x.com/98tml"
  weight = 30

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "投稿一覧"
  pageRef = "posts"
  weight = 5

# [[footer]]
#   pre = "tag"
#   name = "タグ"
#   pageRef = "tags"
#   weight = 10

 [[footer]]
   #pre = "substack"
   name = "カテゴリ"
   pageRef = "categories"
   weight = 20
  
[[footer]]
  #pre = "envelope"
  name = "お問い合わせ"
  url = "https://t98.info/contact/"
  weight = 38

[[footer]]
  name = "利用規約"
  url = "https://doc.t98.info/rule/"
  weight = 39

[[footer]]
  name = "プライバシーポリシー"
  url = "https://doc.t98.info/policy/"
  weight = 40

#[[footer]]
#  name = "特定商取引法に基づく表記"