# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "プロフィール"
  pre = "address-card-regular"
  pageRef = "about"
  weight = 5

[[main]]
  name = "スケジュール"
  pre = "calendar-check-regular"
  pageRef = "eventlist/"
  weight = 11

[[main]]
  name = "撮影依頼"
  pre = "camera-solid"
  pageRef = "shooting-service/"
  weight = 12

[[main]]
  name = "作例"
  pre = "images-regular"
  url = "https://x.com/search?q=%4098tml%20filter%3Amedia%20min_retweets%3A5%20-from%3A98tml&f=media"
  weight = 13

[[main]]
  name = "通販"
  pre = "store-solid"
  url = "https://www.melonbooks.co.jp/circle/?circle_id=119704"
  weight = 14

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/98tml"
  weight = 40

#[[main]]
#  identifier = "instagram"
#  pre = "instagram"
#  url = "https://www.instagram.com/98tml/"
#  weight = 40

[[main]]
  identifier = "contact"
  pre = "envelope"
  url = "https://t98.info/contact/"
  weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "News"
  pageRef = "posts"
  weight = 100

[[footer]]
  #pre = "substack"
  name = "Recruit"
  pageRef = "categories/recruit/"
  weight = 110

# [[footer]]
#   pre = "tag"
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories/"
  weight = 120

[[footer]]
  name = "Rule"
  url = "https://doc.t98.info/rule/"
  weight = 170

[[footer]]
  name = "Policy"
  url = "https://doc.t98.info/policy/"
  weight = 180

[[footer]]
  name = "Shop"
  url = "https://www.melonbooks.co.jp/circle/index.php?circle_id=119704"
  weight = 191

[[footer]]
  name = "Contact"
  url = "https://tayori.com/form/77947e5dc4b5f590517b0cc3ed6038aeed5ddb1f"
  weight = 192